[package]
name = "ursus-pipelines"
version = "0.1.0"
edition = "2021"

[dependencies]
ursus-core = { path = "../ursus-core" }
ursus-materials = { path = "../ursus-materials" }
ursus-gltf-loader = { path = "../ursus-gltf-loader", optional = true }
ursus-obj-loader = { path = "../ursus-obj-loader", optional = true }
ursus-ecs = { path = "../ursus-ecs" }
anyhow = "1"
log = "0.4"
glam = "0.33.0"
resvg = "0.47.0"
bytemuck = "1.25.0"

[features]
default = ["gltf-loader", "obj-loader"]
gltf-loader = ["dep:ursus-gltf-loader"]
obj-loader = ["dep:ursus-obj-loader"]