mod image_alloc;
mod mipmap;
mod staging;

use crate::render::gfx::types::Format;
use crate::vulkan::core::memory::destroy_image_resources;
use crate::vulkan::core::{DeviceContext, SubmitContext};
use ash::vk;
use image_alloc::AllocatedTextureImage;
use staging::StagingBuffer;

pub struct GpuTexture {
    pub image: vk::Image,
    pub view: vk::ImageView,
    pub memory: vk::DeviceMemory,
    pub format: vk::Format,
    pub width: u32,
    pub height: u32,
    pub name: String,
    device: ash::Device,
}

pub struct TextureSource<'a> {
    pub pixels: &'a [u8],
    pub width: u32,
    pub height: u32,
    pub format: Format,
    pub name: &'a str,
}

impl GpuTexture {
    /// Loads a texture with a full mip chain (generated by blitting from mip 0).
    pub fn upload(ctx: DeviceContext, submit: SubmitContext, source: TextureSource) -> anyhow::Result<Self> {
        let mip_levels = compute_mip_levels(source.width, source.height);
        let usage =
            vk::ImageUsageFlags::TRANSFER_DST | vk::ImageUsageFlags::TRANSFER_SRC | vk::ImageUsageFlags::SAMPLED;

        Self::upload_impl(ctx, submit, source, mip_levels, usage, true)
    }

    /// Loads a texture without a mip chain (mip 0 only).
    pub fn upload_no_mip(ctx: DeviceContext, submit: SubmitContext, source: TextureSource) -> anyhow::Result<Self> {
        let usage = vk::ImageUsageFlags::TRANSFER_DST | vk::ImageUsageFlags::SAMPLED;

        Self::upload_impl(ctx, submit, source, 1, usage, false)
    }

    fn upload_impl(
        ctx: DeviceContext,
        submit: SubmitContext,
        source: TextureSource,
        mip_levels: u32,
        usage: vk::ImageUsageFlags,
        with_mipchain: bool,
    ) -> anyhow::Result<Self> {
        let name = source.name.to_string();

        let staging = StagingBuffer::upload(ctx, source.pixels)?;
        let alloc = AllocatedTextureImage::create(ctx, source.format, source.width, source.height, mip_levels, usage)?;

        one_shot(ctx.device, submit, |cmd| {
            if with_mipchain {
                mipmap::upload_with_mipchain(
                    ctx.device,
                    cmd,
                    alloc.image,
                    staging.buffer,
                    source.width,
                    source.height,
                    mip_levels,
                );
            } else {
                mipmap::upload_single_level(ctx.device, cmd, alloc.image, staging.buffer, source.width, source.height);
            }
        })?;

        let view = alloc.create_view(source.format, mip_levels)?;
        let (image, memory) = alloc.into_raw();

        log::debug!(
            "GpuTexture '{}': {}x{} {:?} ({} mip levels)",
            name,
            source.width,
            source.height,
            source.format,
            mip_levels
        );

        Ok(Self {
            image,
            view,
            memory,
            format: source.format.to_vk(),
            width: source.width,
            height: source.height,
            name,
            device: ctx.device.clone(),
        })
    }
}

impl Drop for GpuTexture {
    fn drop(&mut self) {
        unsafe { destroy_image_resources(&self.device, self.image, self.view, self.memory) }
    }
}

/// Number of mip levels for a `width x height` texture. If either dimension is 0, returns 1 level.
/// (An empty/invalid texture must not result in an invalid `log2`.)
fn compute_mip_levels(width: u32, height: u32) -> u32 {
    if width == 0 || height == 0 {
        return 1;
    }
    (width.max(height) as f32).log2().floor() as u32 + 1
}

fn one_shot(device: &ash::Device, submit: SubmitContext, f: impl FnOnce(vk::CommandBuffer)) -> anyhow::Result<()> {
    let alloc_info = vk::CommandBufferAllocateInfo::default()
        .command_pool(submit.command_pool)
        .level(vk::CommandBufferLevel::PRIMARY)
        .command_buffer_count(1);
    let cmd = unsafe { device.allocate_command_buffers(&alloc_info)?[0] };

    unsafe {
        device.begin_command_buffer(
            cmd,
            &vk::CommandBufferBeginInfo::default().flags(vk::CommandBufferUsageFlags::ONE_TIME_SUBMIT),
        )?;
    }

    f(cmd);

    unsafe {
        device.end_command_buffer(cmd)?;
        device.queue_submit(
            submit.queue,
            &[vk::SubmitInfo::default().command_buffers(std::slice::from_ref(&cmd))],
            vk::Fence::null(),
        )?;
        device.queue_wait_idle(submit.queue)?;
        device.free_command_buffers(submit.command_pool, &[cmd]);
    }

    Ok(())
}
