[package]
name = "ursus-demo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sponza-scene-demo"
path = "src/sponza_scene_demo.rs"

[[bin]]
name = "interpolation-demo"
path = "src/interpolation_demo.rs"

[dependencies]
ursus-core = { path = "../ursus-core" }
ursus-pipelines = { path = "../ursus-pipelines" }
engine-materials = { path = "../engine-materials" }
engine-gltf-loader = { path = "../engine-gltf-loader" }
anyhow = "1"
log = "0.4"
glam = "0.33.0"
resvg = "0.48.1"